### ISSUE TITLE
Issue with GTOPO30.tif

### ISSUE THREAD

**Issue by wthuiller** [vdicolab/hsdm#7]
Dear reader,

We are having an issue with GTOPO30.tif that is used page 72 of the book. We cannot put in the GitHub any longer because it is too heavy. Our fault, we have not thought we'll have size limit on GitHub. It means that the command line 
elev <- raster('raster/topo/GTOPO30.tif') cannot work for the moment (we are working on resolving that issue) and the following bbox either. 

There are two solutions so far. 

1) Download the GTOPO30 file on your own, but it is composed of several tiles that need to be merged. Find it here: https://ngdc.noaa.gov/mgg/topo/gltiles.html
I will quickly post a code for downloading them and merging them soon. 

2) The second option is simply to skip that part of the code. 
In page 73, the command
elev1 <- resample(elev, bio7, method='ngb') 
should then be replaced by 
elev1 <- raster('raster/topo/elev1.grd')

The next lines should then work properly. 

Best regards
Wilfried

**Comment by apsomas** [comment]
Dear reader,

The raster data required for running the code on the book that could not be stored on Github due to size restrictions can be accessed from here:

- GTOPO 30: https://www.wsl.ch/lud/HSDM_Book_Data/GTOPO_30.zip
- PRISM precipitation: https://www.wsl.ch/lud/HSDM_Book_Data/prec_30yr_normal_annual.zip
- PRISM temperature: https://www.wsl.ch/lud/HSDM_Book_Data/tave_30yr_normal_annual.zip
- Landsat 5: https://www.wsl.ch/lud/HSDM_Book_Data/Landsat5.zip

Kind regards,
Achilleas.

**Comment by dsteinke2017** [comment]
Just tried to download these files. Unfortunately, it returns a "Forbidden You don't have permission to access this resource".
Is there an alternate link?
Thanks a lot
Dirk
